name: SMART Maker
favicon: null
layout_spectrum: 1
typography_spectrum: 0.875417688395828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8ed8f8'
    - '#feca05'
    - '#da5f26'
    - '#2d59a4'
  brandStrength: 0.5
  lightness: 0.4640300124883652
  saturation: 0.3718110234476626
  rhythmicContrast: 0.28315324150025845
purpose: []
